# Generated by Django 2.2.3 on 2019-07-25 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('superheroes', '0001_initial'), ('superheroes', '0002_auto_20171102_0712'), ('superheroes', '0003_superhero_favorite_fruit')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Power',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('description', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('powers', models.ManyToManyField(to='superheroes.Power')),
            ],
        ),
        migrations.CreateModel(
            name='Superhero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('real_name', models.CharField(max_length=32)),
                ('secret_identity', models.CharField(max_length=32)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superheroes.City')),
                ('enemies', models.ManyToManyField(to='superheroes.Enemy')),
                ('powers', models.ManyToManyField(to='superheroes.Power')),
                ('favorite_fruit', models.CharField(default='', max_length=32)),
            ],
        ),
    ]
