# Generated by Django 2.2.3 on 2019-07-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superheroes', '0002_superhero_secret_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superhero',
            name='secret_number',
            field=models.FloatField(default=1),
        ),
    ]
