# Generated by Django 2.2.3 on 2019-07-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superheroes', '0002_auto_20171102_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='superhero',
            name='favorite_fruit',
            field=models.CharField(default='', max_length=32),
        ),
    ]
