# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-16 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superheroes', '0004_auto_20171116_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='superhero',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
