# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-16 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superheroes', '0006_superhero_favorite_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='superhero',
            name='weakness',
            field=models.CharField(default='Doughnuts', max_length=32),
            preserve_default=False,
        ),
    ]
