# Generated by Django 2.2.3 on 2019-07-25 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superheroes', '0003_auto_20190725_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superhero',
            name='secret_number',
        ),
    ]
