# Generated by Django 2.2.3 on 2019-07-25 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superheroes', '0004_remove_superhero_secret_number'),
    ]

    operations = [
    ]
