# Generated by Django 2.2.3 on 2019-07-25 17:45

from django.db import migrations

# function to modify databse
def combine_last_name_first_name(apps, schema_editor):
    Person = apps.get_model('yourappname', 'Person')
    for person in Person.objects.all():
        person.name = '%s %s' % (person.first_name, person.last_name)
        person.save()

class Migration(migrations.Migration):


    dependencies = [
        ('superheroes', '0005_auto_20190725_1344'),
    ]

    operations = [
        migrations.RunPython(combine_last_name_first_name)
    ]
