# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-13 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superheroes', '0002_auto_20171102_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='power',
            name='level',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
