# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-16 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superheroes', '0007_superhero_weakness'),
    ]

    operations = [
        migrations.AddField(
            model_name='superhero',
            name='height',
            field=models.IntegerField(default=72),
            preserve_default=False,
        ),
    ]
